### ISSUE TITLE
This mod conflicts with fabric api

### ISSUE THREAD

**Issue by KrisCris** [Fallen-Breath/more-statistics#1]
CustomPayloadC2sPacketMixin is conflicting

**Comment by KrisCris** [comment]
改一下。。不是和mcdr冲突。。是和游戏本身冲突，然后服务端就显示不了客户端发过来的消息了，mcdr就没法解析了

**Comment by KrisCris** [comment]
[16:44:04] [Netty Server IO #1/WARN]: Method overwrite conflict for getPacketChannel in carpet.mixins.json:CustomPayloadC2SPacketMixin, previously written by me.fallenbreath.morestatistics.mixins.CustomPayloadC2SPacketMixin. Skipping method.
[16:44:04] [Netty Server IO #1/WARN]: Method overwrite conflict for getPacketData in carpet.mixins.json:CustomPayloadC2SPacketMixin, previously written by me.fallenbreath.morestatistics.mixins.CustomPayloadC2SPacketMixin. Skipping method.

**Comment by KrisCris** [comment]
<img width="509" alt="Screen Shot 2020-08-07 at 4 46 41 PM" src="https://user-images.githubusercontent.com/38860226/89627507-9355f200-d8cd-11ea-8c2c-d65f7c8db7f1.png">
<img width="428" alt="Screen Shot 2020-08-07 at 4 46 50 PM" src="https://user-images.githubusercontent.com/38860226/89627514-981aa600-d8cd-11ea-8dc2-214b1dceb6ef.png">

**Comment by KrisCris** [comment]
版本1.16.1

**Comment by Fallen-Breath** [comment]
具体使用了什么mod设么环境？我在1.16.1一切正常

**Comment by KrisCris** [comment]
这样嘛，那我先排除一下看看

**Comment by KrisCris** [comment]
我感觉他是不是和所有需要客户端和服务端两头的mod都冲突啊😂

**Comment by KrisCris** [comment]
<img width="412" alt="Screen Shot 2020-08-07 at 5 42 46 PM" src="https://user-images.githubusercontent.com/38860226/89632811-6b6a8c80-d8d5-11ea-8b1c-9c0c89cd5b4a.png">
我放在unmods文件夹里的mod全都没法用😂

**Comment by KrisCris** [comment]
https://www.curseforge.com/minecraft/mc-mods/fabric-tree-chopper
https://www.curseforge.com/minecraft/mc-mods/beenfo
https://www.curseforge.com/minecraft/mc-mods/diggus-maximus
https://www.curseforge.com/minecraft/mc-mods/simpleharvest
https://www.curseforge.com/minecraft/mc-mods/presence-footsteps
https://www.curseforge.com/minecraft/mc-mods/inventory-sorting

**Comment by Lolion11** [comment]
我遇到了一样的问题，在和依赖fabric api的mod一起用的时候会导致自带语言文件被覆盖，把mod里的语言文件删掉就正常了。

**Comment by plusls** [comment]
比较尴尬，我也碰上了这个问题

一般 mod 的语言文件应该在 `src\main\resources\assets\mod_id\lang` ？

不知道是不是这个引起的

**Comment by Fallen-Breath** [comment]
> 比较尴尬，我也碰上了这个问题
> 
> 一般 mod 的语言文件应该在 `src\main\resources\assets\mod_id\lang` ？
> 
> 不知道是不是这个引起的

应该是因为这个引起的

对于这个 mod 来说，在无 fabric api 的情况下可运行的优先级是大于兼容 fabric api 的，因此我并不会为了 fabric api 而主动去修改

**Comment by plusls** [comment]
> > 比较尴尬，我也碰上了这个问题
> > 一般 mod 的语言文件应该在 `src\main\resources\assets\mod_id\lang` ？
> > 不知道是不是这个引起的
> 
> 应该是因为这个引起的
> 
> 对于这个 mod 来说，在无 fabric api 的情况下可运行的优先级是大于兼容 fabric api 的，因此我并不会为了 fabric api 而主动去修改

src\main\resources\assets\mod_id\lang 这个位置的语言文件是由 fabric-api 去加载的么（我一直以为是 fabric loader 加载的

**Comment by plusls** [comment]
如果是这样应该可以考虑 copy 一下 fabric api 的实现来手动加载一下？（工作量++

好奇 fabric api 打破了啥 mod 的兼容性

**Comment by Fallen-Breath** [comment]
已于 v2.0.0 中修复
