### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by little-mimua** [Fallen-Breath/more-statistics#5]
How should I create a block placement list?

**Comment by Fallen-Breath** [comment]
The same as vanilla statistic / citeria, see https://minecraft.fandom.com/wiki/Scoreboard#Criteria

**Comment by little-mimua** [comment]
> 与香草统计/柠檬相同，请参阅 https://minecraft.fandom.com/wiki/Scoreboard#Criteria

Thank you
